# Generated by Django 3.2.10 on 2023-09-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frondend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(blank=True, max_length=20, null=True)),
                ('ProName', models.CharField(blank=True, max_length=20, null=True)),
                ('Description', models.CharField(blank=True, max_length=200, null=True)),
                ('Quantity', models.IntegerField(blank=True, null=True)),
                ('TotalPrice', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
