# Generated by Django 3.2.10 on 2023-09-14 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frondend', '0003_cartdb_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartdb',
            name='Image',
        ),
    ]
