# Generated by Django 3.2.10 on 2023-09-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frondend', '0005_cartdb_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdb',
            name='Status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
