# Generated by Django 3.2.10 on 2023-09-15 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frondend', '0006_cartdb_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdb',
            name='Image',
            field=models.ImageField(blank=True, default="{% static '1.png' %}", null=True, upload_to='dp'),
        ),
    ]
