# Generated by Django 3.2.10 on 2023-09-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frondend', '0007_userdb_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdb',
            name='Image',
            field=models.ImageField(blank=True, default='1.png', null=True, upload_to='dp'),
        ),
    ]
