# Generated by Django 3.2.10 on 2023-09-15 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frondend', '0008_alter_userdb_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdb',
            name='Address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
