# Generated by Django 3.2.10 on 2023-09-15 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frondend', '0009_userdb_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessagesDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(blank=True, max_length=100, null=True)),
                ('Message', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
