# Generated by Django 3.2.10 on 2023-09-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frondend', '0010_messagesdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagesdb',
            name='Message',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
