# Generated by Django 3.2.10 on 2023-09-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdb',
            name='Image',
        ),
        migrations.AddField(
            model_name='productdb',
            name='Image1',
            field=models.ImageField(blank=True, null=True, upload_to='ProductImages'),
        ),
        migrations.AddField(
            model_name='productdb',
            name='Image2',
            field=models.ImageField(blank=True, null=True, upload_to='ProductImages'),
        ),
        migrations.AddField(
            model_name='productdb',
            name='Image3',
            field=models.ImageField(blank=True, null=True, upload_to='ProductImages'),
        ),
    ]
