# Generated by Django 3.2.10 on 2023-09-12 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_rename_image3_productdb_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdb',
            name='Image',
        ),
        migrations.RemoveField(
            model_name='productdb',
            name='Image1',
        ),
        migrations.RemoveField(
            model_name='productdb',
            name='Image2',
        ),
    ]
