# Generated by Django 3.2.10 on 2023-09-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0005_auto_20230912_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdb',
            name='ProColor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productdb',
            name='ProSize',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productdb',
            name='StockQty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
