# Generated by Django 3.2.10 on 2023-09-13 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0006_auto_20230912_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdb',
            name='ProColor',
        ),
        migrations.RemoveField(
            model_name='productdb',
            name='ProSize',
        ),
    ]
